### ISSUE TITLE
your code sucks

### ISSUE THREAD

**Issue by Owais-Eltigani** [JermineJunior/Student-Management-System#1]
you still using vue & php ?! you better try nextJS and server components

**Comment by khatabwedaa** [comment]
Man, be more respectful @Owais-Eltigani

**Comment by JermineJunior** [comment]
Well if @Owais-Eltigani complains then u must be doing something right

**Comment by Owais-Eltigani** [comment]
😂😂 @khatabwedaa

**Comment by Owais-Eltigani** [comment]
not like that but vueJS is not meta anymore
